<a href="https://colab.research.google.com/github/qjrmanalo25-dev/CPE-310-2526A/blob/main/Final_Case_Study_Netflix_Dataset_(Group_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Data Loading & Overview. Load the CSV into a DataFrame. What are its dimensions (.shape)? Display the first and last five rows. What insights do you immediately notice about the columns?

In [ ]:
import pandas as pd

df = pd.read_csv("/netflix_titles.csv")
df.shape

(8807, 12)

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

2) Data Cleaning. Which columns contain missing values? How might you handle missing entries? Drop them or fill with a placeholder?

In [ ]:
import pandas as pd

df = pd.read_csv("/netflix_titles.csv")

df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
import pandas as pd
df = pd.read_csv("/netflix_titles.csv")

df['director'] = df['director'].fillna("Unknown")
df['cast'] = df['cast'].fillna("Not Available")
df['country'] = df['country'].fillna("Unknown")
df['rating'] = df['rating'].fillna("Not Rated")
df['duration'] = df['duration'].fillna("Unknown")
df['date_added'] = df['date_added'].fillna("Not Specified")

print(df.head())
print(df.tail())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water          Unknown
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans          Unknown
4      s5  TV Show           Kota Factory          Unknown

                                                cast        country  \
0                                      Not Available  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...        Unknown
3                                      Not Available        Unknown
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...
     show_id     type        title         director  \
8802   s8803    Movie       Zodiac    David Fincher
8803   s8804  TV Show  Zombie Dumb          Unknown
8804   s8805    Movie   Zombieland  Ruben Fleischer
8805   s8806    Movie         Zoom     Peter Hewitt
8806   s8807    Movie       Zubaan      Mozez Singh

                                                   cast        country  \
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                      Not Available        Unknown
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

             date_added  release_year rating   duration  \
8802  November 20, 2019          2007      R    158 min
8803       July 1, 2019          2018  TV-Y7  2 Seasons
8804   November 1, 2019          2009      R     88 min
8805   January 11, 2020          2006     PG     88 min
8806      March 2, 2019          2015  TV-14    111 min

                                           listed_in  \
8802                  Cult Movies, Dramas, Thrillers
8803          Kids' TV, Korean TV Shows, TV Comedies
8804                         Comedies, Horror Movies
8805              Children & Family Movies, Comedies
8806  Dramas, International Movies, Music & Musicals

                                            description
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

3) Data Types & Conversion. Check each column’s data type. Are there any that you need to convert (like date to datetime type)?

In [7]:
import pandas as pd
df = pd.read_csv("/netflix_titles.csv")
print(df.dtypes)

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

print(df.dtypes)

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object
show_id                 object
type                    object
title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
description             object
dtype: object

4) Univariate Analysis. How many Movies vs. TV Shows are there? What are the top five most common ratings? Which release year appears most frequently?

In [ ]:
type_counts = df['type'].value_counts()
print("Movies vs TV Shows:\n", type_counts)

Movies vs TV Shows:
 type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [ ]:
top_ratings = df['rating'].value_counts().head(5)
print("\nTop 5 Ratings:\n", top_ratings)

Top 5 Ratings:
 rating
TV-MA    3207
TV-14    2160
TV-PG     863
R         799
PG-13     490
Name: count, dtype: int64

In [ ]:
common_year = df['release_year'].value_counts().idxmax()
print("\nMost Common Release Year:", common_year)

Most Common Release Year: 2018

5) Duration & Seasons. Parse duration into numeric minutes (for movies) and number of seasons (for shows). What is the average movie length? The average number of seasons per TV show?

In [ ]:
movies = df[df['type'] == 'Movie'].copy()
tv_shows = df[df['type'] == 'TV Show'].copy()

movies['duration'] = movies['duration'].str.replace(' min', '', regex=False).astype(float)

tv_shows['duration'] = tv_shows['duration'].str.replace(' Seasons', '', regex=False)
tv_shows['duration'] = tv_shows['duration'].str.replace(' Season', '', regex=False).astype(float)

avg_movie_length = movies['duration'].mean()
print("Average movie length (minutes):", avg_movie_length)

avg_seasons = tv_shows['duration'].mean()
print("Average number of seasons:", avg_seasons)

Average movie length (minutes): 99.57718668407311
Average number of seasons: 1.764947683109118

6) Genre Analysis. Which genre has the highest average release year? What might that indicate?

In [ ]:
df['genre'] = df['listed_in'].str.split(',')
df_exploded = df.explode('genre')
df_exploded['genre'] = df_exploded['genre'].str.strip()
genre_avg = df_exploded.groupby('genre')['release_year'].mean()
genre_avg = genre_avg.sort_values(ascending=False)
print(genre_avg.head())

genre
TV Mysteries                    2018.346939
TV Horror                       2018.200000
Reality TV                      2017.894118
Stand-Up Comedy & Talk Shows    2017.857143
TV Thrillers                    2017.736842
Name: release_year, dtype: float64

7) Temporal Trends. Are there spikes or drops? Compare release_year vs. year_added: how long after release does Netflix typically acquire content?

In [ ]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year

titles_per_year = df['year_added'].value_counts().sort_index()
print(titles_per_year)

df['lag'] = df['year_added'] - df['release_year']

print("Average lag:", df['lag'].mean())
print("Median lag:", df['lag'].median())

year_added
2008.0       2
2009.0       2
2010.0       1
2011.0      13
2012.0       3
2013.0      10
2014.0      23
2015.0      73
2016.0     418
2017.0    1164
2018.0    1625
2019.0    1999
2020.0    1878
2021.0    1498
Name: count, dtype: int64
Average lag: 4.690894476977839
Median lag: 1.0

8) Rating vs. Type. Create a cross-tab or pivot table of type vs. rating. Which rating dominates movies compared to TV shows?

In [8]:
cross_tab = pd.crosstab(df['type'], df['rating'])

print(cross_tab)

print("\nTop ratings for Movies:")
print(cross_tab.loc['Movie'].sort_values(ascending=False).head())

print("\nTop ratings for TV Shows:")
print(cross_tab.loc['TV Show'].sort_values(ascending=False).head())

rating   66 min  74 min  84 min   G  NC-17  NR   PG  PG-13    R  TV-14  TV-G  \
type
Movie         1       1       1  41      3  75  287    490  797   1427   126
TV Show       0       0       0   0      0   5    0      0    2    733    94

rating   TV-MA  TV-PG  TV-Y  TV-Y7  TV-Y7-FV  UR
type
Movie     2062    540   131    139         5   3
TV Show   1145    323   176    195         1   0

Top ratings for Movies:
rating
TV-MA    2062
TV-14    1427
R         797
TV-PG     540
PG-13     490
Name: Movie, dtype: int64

Top ratings for TV Shows:
rating
TV-MA    1145
TV-14     733
TV-PG     323
TV-Y7     195
TV-Y      176
Name: TV Show, dtype: int64

9) Filtering & Querying. Extract all titles with rating “R” added after 2020. How many?

In [9]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

filtered = df[(df['rating'] == 'R') & (df['date_added'].dt.year > 2020)]

print(filtered[['title', 'rating', 'date_added']])

print("Total count:", len(filtered))

                                title rating date_added
46                         Safe House      R 2021-09-16
48                       Training Day      R 2021-09-16
81                               Kate      R 2021-09-10
122                        In the Cut      R 2021-09-02
131       Blade Runner: The Final Cut      R 2021-09-01
...                               ...    ...        ...
8072                  Spring Breakers      R 2021-01-10
8106                       Striptease      R 2021-01-01
8126                         Superbad      R 2021-01-01
8272                     The Departed      R 2021-01-01
8320  The Girl with the Dragon Tattoo      R 2021-01-05

[190 rows x 3 columns]
Total count: 190

10) Aggregations & GroupBy. For each country, compute the average release year of its titles. Group by year_added and compute the proportion of Movies vs. TV Shows added each year.

In [ ]:
df = pd.read_csv("/netflix_titles.csv")

df['release_year'] = pd.to_numeric(df['release_year'], errors='coerce')
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['year_added'] = df['date_added'].dt.year
df = df.dropna(subset=['country', 'year_added'])

avg_release_year = df.groupby('country')['release_year'].mean().reset_index()

print("Average Release Year per Country:")
display(avg_release_year.head(10))

counts = df.groupby(['year_added', 'type']).size().unstack(fill_value=0)
proportions = counts.div(counts.sum(axis=1), axis=0)

print("\nProportion of Movies vs TV Shows per Year Added:")
display(proportions.head(10))

Average Release Year per Country:

                                             country  release_year
0                                  , France, Algeria       2014.00
1                                      , South Korea       2021.00
2                                          Argentina       2016.00
3  Argentina, Brazil, France, Poland, Germany, De...       2017.00
4                                   Argentina, Chile       2011.50
5                             Argentina, Chile, Peru       2015.00
6                                  Argentina, France       2017.00
7   Argentina, France, United States, Germany, Qatar       2017.00
8                                   Argentina, Italy       2017.00
9                                   Argentina, Spain       2012.25

Proportion of Movies vs TV Shows per Year Added:

type           Movie   TV Show
year_added
2008.0      0.500000  0.500000
2009.0      1.000000  0.000000
2010.0      1.000000  0.000000
2011.0      1.000000  0.000000
2012.0      1.000000  0.000000
2013.0      0.600000  0.400000
2014.0      0.826087  0.173913
2015.0      0.771429  0.228571
2016.0      0.611529  0.388471
2017.0      0.740673  0.259327

11) Applying Functions. Write a function that, given a director’s name, returns their titles sorted by release_year. Create a reusable function to plot the top N categories for any categorical column.

In [ ]:
df = pd.read_csv("/netflix_titles.csv")

df['release_year'] = pd.to_numeric(df['release_year'], errors='coerce')

def get_titles_by_director(df, director_name):

    filtered = df[df['director'].str.contains(director_name, case=False, na=False)]

    result = filtered.sort_values(by='release_year')[['title', 'release_year', 'type']]

    return result

print("=== Titles by Director ===")
display(get_titles_by_director(df, "Steven Spielberg"))

def plot_top_n_categories(df, column, n=10):

    top_counts = df[column].value_counts().head(n)

    plt.figure()
    top_counts.plot(kind='bar')

    plt.title(f"Top {n} Categories in '{column}'")
    plt.xlabel(column)
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    plt.grid()

    plt.show()

=== Titles by Director ===

                                                  title  release_year   type
41                                                 Jaws          1975  Movie
7072      Indiana Jones and the Raiders of the Lost Ark          1981  Movie
7073               Indiana Jones and the Temple of Doom          1984  Movie
7071                 Indiana Jones and the Last Crusade          1989  Movie
7957                                   Schindler's List          1993  Movie
329                                 Catch Me If You Can          2002  Movie
7070  Indiana Jones and the Kingdom of the Crystal S...          2008  Movie
8184                           The Adventures of Tintin          2011  Movie
8696                                          War Horse          2011  Movie
7308                                            Lincoln          2012  Movie
1203                                            The BFG          2016  Movie